name: MetnaVadq
description: "Beta app for course work 2023/2024"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  flutter_secure_storage: ^9.0.0
  dio: ^5.4.0
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  auto_route: ^7.8.4
  go_router: ^13.1.0
  equatable: ^2.0.5
  loadmore: ^2.1.0
  flutter_map: ^6.1.0
  flutter_map_marker_cluster: ^1.3.4
  latlong2: ^0.9.0
  geolocator: ^11.0.0
  font_awesome_flutter: ^10.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8
  custom_lint: ^0.5.8
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true
  assets:
    - lib/assets/pictures/